// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUD.Models
{
    [Table("Customer_Details")]
    public partial class CustomerDetails
    {
        [Key]
        [Column("Cust_Id")]
        public int CustId { get; set; }
        [Column("Cust_Name")]
        [StringLength(50)]
        public string CustName { get; set; }
        [Column("Cust_Add")]
        [StringLength(50)]
        public string CustAdd { get; set; }
        [Column("Cust_Email")]
        [StringLength(50)]
        public string CustEmail { get; set; }
        [Column("Cust_Mob_No")]
        public long? CustMobNo { get; set; }
    }
}